"""empty message

Revision ID: 3345f294f908
Revises: 775dca0fdf26
Create Date: 2020-09-09 18:33:44.975471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3345f294f908'
down_revision = '775dca0fdf26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'value')
    # ### end Alembic commands ###
