"""empty message

Revision ID: 414bb9c0a486
Revises: b6b000f3f36e
Create Date: 2020-09-09 20:01:29.835242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414bb9c0a486'
down_revision = 'b6b000f3f36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'contributors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('contributors', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
