"""empty message

Revision ID: 59b67c76a957
Revises: 62902d724aab
Create Date: 2020-09-11 08:01:56.176313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b67c76a957'
down_revision = '62902d724aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('campaign_contributor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('campaigns', sa.Column('value', sa.Float(), nullable=True))
    op.drop_column('campaigns', 'contributors')
    op.add_column('requests', sa.Column('eth_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'eth_id')
    op.add_column('campaigns', sa.Column('contributors', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('campaigns', 'value')
    op.drop_table('campaign_contributor')
    op.drop_table('contributor')
    # ### end Alembic commands ###
