"""empty message

Revision ID: 661d1ce96a5b
Revises: 3345f294f908
Create Date: 2020-09-09 19:48:02.356818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661d1ce96a5b'
down_revision = '3345f294f908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'value')
    # ### end Alembic commands ###
