"""empty message

Revision ID: 775dca0fdf26
Revises: c6fd694c96de
Create Date: 2020-09-09 18:15:52.973151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775dca0fdf26'
down_revision = 'c6fd694c96de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'value')
    # ### end Alembic commands ###
