"""empty message

Revision ID: c6fd694c96de
Revises: f036d3d097a5
Create Date: 2020-09-09 17:43:16.881915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6fd694c96de'
down_revision = 'f036d3d097a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'value')
    # ### end Alembic commands ###
