"""empty message

Revision ID: ff09bc594003
Revises: f036d3d097a5
Create Date: 2020-09-10 11:14:49.303602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff09bc594003'
down_revision = 'f036d3d097a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('eth_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'eth_id')
    # ### end Alembic commands ###
