"""empty message

Revision ID: ff7e6ddd103d
Revises: 414bb9c0a486
Create Date: 2020-09-09 20:14:19.765842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7e6ddd103d'
down_revision = '414bb9c0a486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contributor', ['address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contributor', type_='unique')
    # ### end Alembic commands ###
